language: java

jdk:
    - oraclejdk8
    - openjdk8
    - oraclejdk9

services:
      - postgresql

before_script:
      - psql -c $'create role "mongo-java-server-test" login password \'mongo-java-server-test\';' -U postgres
      - psql -c 'create database "mongo-java-server-test" with owner = "mongo-java-server-test";' -U postgres

addons:
      postgresql: "9.5"
