language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk8

services:
      - postgresql

before_script:
      - psql -c $'create role "mongo-java-server-test" login password \'mongo-java-server-test\';' -U postgres
      - psql -c 'create database "mongo-java-server-test" with owner = "mongo-java-server-test";' -U postgres

addons:
      postgresql: "9.5"
