version: '2.1'

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres-mongo-java-server-test
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=mongo-java-server-test
      - POSTGRES_PASSWORD=mongo-java-server-test
      - POSTGRES_DB=mongo-java-server-test
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
